# -*- coding: utf-8 -*-
"""Waste_segregation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gsO9EDhl7x18y8hAVijo7R1o_QTd1pLT
"""

from google.colab import drive
drive.mount('/content/drive')

# importing custom Images from drive and resizing each images into size of 224x224
import os
from PIL import Image

main_folder_path = "/content/drive/MyDrive/Garbage"

IMG_SIZE = (224, 224)
for class_name in os.listdir(main_folder_path):
    class_path = os.path.join(main_folder_path, class_name)
    new_class_path = os.path.join(main_folder_path + "_resized4", class_name)
    os.makedirs(new_class_path, exist_ok=True)
    for file_name in os.listdir(class_path):
        if file_name.endswith(".jpg"):
            img_path = os.path.join(class_path, file_name)
            try:
                img = Image.open(img_path).convert("RGB")
                img_resized = img.resize(IMG_SIZE)
                if img_resized.size == IMG_SIZE:
                    new_img_path = os.path.join(new_class_path, file_name)
                    img_resized.save(new_img_path, "JPEG")
                    print("Resized image saved to", new_img_path, "with shape", img_resized.size)
                else:
                    print("Image size not correct:", img_path, "with shape", img_resized.size)
                    os.remove(img_path)
            except Exception as e:
                print(f"Error processing {img_path}: {str(e)}")
                continue

from tensorflow.keras.preprocessing.image import ImageDataGenerator


main_folder_path = "/content/drive/MyDrive/Garbage_resized4"

# Define the data generator and specify the data augmentation parameters
datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    vertical_flip=False,
    brightness_range=[0.2,1.0],
    validation_split=0.2
)
batch_size = 32
# training data
train_generator = datagen.flow_from_directory(
    main_folder_path,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training'
)

# validation data
val_generator = datagen.flow_from_directory(
    main_folder_path,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation'
)

# Three classes and its shape of each image in each class
import os
import numpy as np
from PIL import Image

main_folder_path = "/content/drive/MyDrive/Garbage_resized4"

def get_num_files(directory):
    count = 0
    for filename in os.listdir(directory):
        if os.path.isfile(os.path.join(directory, filename)):
            count += 1
    return count

for class_name in os.listdir(main_folder_path):
    class_path = os.path.join(main_folder_path, class_name)
    num_files = get_num_files(class_path)
    print(class_name)
    print("Number of files:", num_files)
    img_path = os.path.join(class_path, os.listdir(class_path)[0])
    img = Image.open(img_path)
    print("Shape of the image:", img.size)

import os
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Set the path to the main folder containing the subfolders
main_folder_path = "/content/drive/MyDrive/Garbage_resized4"

# Define image generator and specify the desired preprocessing steps
image_generator = ImageDataGenerator(rescale=1./255, validation_split=0.2)

# Define batch size
batch_size = 32

# Generate training data
train_data = image_generator.flow_from_directory(
    directory=main_folder_path,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode="categorical",
    subset="training",
)

# Generate validation data
val_data = image_generator.flow_from_directory(
    directory=main_folder_path,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode="categorical",
    subset="validation",
)

# Print the number of classes
num_classes = len(train_data.class_indices)
print("Number of classes:", num_classes)

# Print the shape of the training and validation data
print("Shape of training data:", train_data[0][0].shape)
print("Shape of validation data:", val_data[0][0].shape)

# Load the image data and printing its shape of X and y
import os
from PIL import Image
import numpy as np
from tensorflow.keras.utils import to_categorical
def load_data():
    main_folder_path = "/content/drive/MyDrive/Garbage_resized4"
    class_map = {'biodegradable': 0,'hazardous': 1,'nonbiodegradable': 2}
    images = []
    labels = []
    for class_name in os.listdir(main_folder_path):
        class_path = os.path.join(main_folder_path, class_name)
        for file_name in os.listdir(class_path):
            if file_name.endswith(".jpg"):
                img_path = os.path.join(class_path, file_name)
                img = Image.open(img_path)
                img_array = np.array(img)
                images.append(img_array)
                label = to_categorical(class_map[class_name], num_classes=3)
                labels.append(label)
    return np.array(images), np.array(labels)
X, y = load_data()
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)





#importing the pretrained model VGG16 adding custom layers to model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.applications.vgg16 import VGG16
from sklearn.model_selection import train_test_split
from keras.applications.vgg16 import VGG16

vgg_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))


for layer in vgg_model.layers:
    layer.trainable = False

model = Sequential()
model.add(vgg_model)
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

from sklearn.model_selection import train_test_split

# Split the data into training, validation, and test sets
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.2, random_state=42)

# Train the model on the training set, validate on the validation set, and evaluate on the test set
history = model.fit(X_train, y_train, batch_size=32, epochs=20, validation_data=(X_val, y_val))

test_loss, test_acc = model.evaluate(X_test, y_test)

print('Test accuracy:', test_acc)

# Test loss and accuracy
loss, accuracy = model.evaluate(X_test, y_test )
print("Test loss:", loss)
print("Test accuracy:", accuracy)

# saving the model
model.save('/content/drive/MyDrive/new_model1.h5')

# Loading the model and start predicting classes based on image data captured by
import cv2
from tensorflow.keras.models import load_model
import numpy as np

# Load the model
model = load_model('Desktop/new_model1.h5')

# Set the expected input size for the model
input_size = (224, 224)

# Start capturing images from the default camera
cap = cv2.VideoCapture(0)

while True:
    # Read a frame from the camera
    ret, frame = cap.read()

    if ret:
        # Display the frame
        cv2.imshow('frame', frame)


        # Wait for the 'c' key to be pressed to capture the image
        if cv2.waitKey(1) & 0xFF == ord('c'):
            # Resize the captured image to the expected input size for the model
            img = cv2.resize(frame, input_size)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            # Make a prediction with the model
            prediction = model.predict(np.expand_dims(img, axis=0))
            predicted_class = np.argmax(prediction)
            print("Predicted class:", predicted_class)

        # Exit the loop when the 'q' key is pressed
        elif cv2.waitKey(1) & 0xFF == ord('q'):
            break

    else:
        # Handle the case where cap.read() failed to read a frame
        print("Error: Failed to read frame from camera")
        break
cap.release()
cv2.destroyAllWindows()

